version: '3'

services:
  backend:
    build: ci/backend
    ports:
    - 8080:8080
    volumes:
    - ./backend:/backend

  frontend:
    build: ci/frontend
    ports:
    - 8081:8080
    volumes:
    - ./frontend:/frontend

  web:
    image: nginx
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    links:
    - backend:backend
    - frontend:frontend
    #entrypoint: [ "/bin/sh", "-c", "sleep 2073600" ]
